### ISSUE TITLE
conect back issue

### ISSUE THREAD

**Issue by tehseensagar** [0blio/caesarRAT#10]
I just setup caesar rat into my parrot os . after setting up every thing I generate payload via python caesar.py file and for server/ip I user my local ip 192.168.200.10 and file generated with test.py .

I ran python test.py  and check my webpanel targets , no target listed there.

Regards

**Comment by 0blio** [comment]
I need some screens of your settings in order to help you.

**Comment by tehseensagar** [comment]
What kind of setting do you required . 

Case-1 : Loopback IP testing
Server-IP : Localhost(127.0.0.1)

No connection

Case-2: LAN 

Server-IP : 192.168.10.200
Client-IP : 192.168.10.201

Yet not connection in both senerio

Regards

**Comment by a-mohamed** [comment]
The Trojan adds itself to the list by contacting "/target/handshake.php"
In the first case, did you try to browse : 127.0.0.1/[PATH_TO_APP]/target/handshake.php  ?
You should get a white page.

**Comment by buittuan1985** [comment]
Hi,
I created file .exe in window, but when I run it nothing happen in Kali Linux.
Can you help me? Thanks

**Comment by 0blio** [comment]
> Hi,
> I created file .exe in window, but when I run it nothing happen in Kali Linux.
> Can you help me? Thanks

You should open a new issue.

**Comment by 0blio** [comment]
Solved.
