### ISSUE TITLE
Database Error!

### ISSUE THREAD

**Issue by Dyotson** [0blio/caesarRAT#3]
Hi, Im trying to run caesar on Ubuntu 17.10, I have installed all the requirements, created the database and everything...

But, I still having the same error of Database Error!, I tried to figure out what is wrong searching for a log or something but not rewarding at all.

**Comment by 0blio** [comment]
Are you using MySql as database? What web server are you using?

**Comment by Dyotson** [comment]
I have already given full permission to the folder, but it still throwing the error

**Comment by Dyotson** [comment]
Im using Apache and MySQL with a database called caesar

**Comment by 0blio** [comment]
I never tried with Apache. For some reason it give me the same error on it. 

In the `/var/log/apache2/error.log` I can read:

`[Fri Feb 16 13:13:26.262101 2018] [:error] [pid 6679] [client 127.0.0.1:39908] PHP Warning:  session_start(): open(/var/lib/php/sessions/sess_3b081re3qkclodlaqcme7d407a, O_RDWR) failed: Permission denied (13) in /var/www/html/caesar/login.php on line 13`
`[Fri Feb 16 13:13:26.262255 2018] [:error] [pid 6679] [client 127.0.0.1:39908] PHP Warning:  Unknown: open(/var/lib/php/sessions/sess_3b081re3qkclodlaqcme7d407a, O_RDWR) failed: Permission denied (13) in Unknown on line 0`
`[Fri Feb 16 13:13:26.262271 2018] [:error] [pid 6679] [client 127.0.0.1:39908] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in Unknown on line 0`

It seems apache is not able to handle sessions without some sort of pre-configuration. I'm actually investigating on it and I will add a little guide on how to set up Caesar on Apache when I'll have solved.
Anyway, for now, if you want to start the server without configurations you can use the PHP built-in server (that I actually use for testing). You can just:
`cd caesarRAT/Server`
`php -S 0.0.0.0:80`

**Comment by Dyotson** [comment]
Alright! Thaaaanks!

**Comment by Dyotson** [comment]
I still having problems with the
`php -S `0.0.0.0:80`

Same error, database error, in the PHP console shows 

[Sun Feb 18 23:23:18 2018] 127.0.0.1:47216 [404]: /favicon.ico - No such file or directory

Not sure whats wrong

**Comment by 0blio** [comment]
It's really strange. It should atleast return a database error in the php console..
Let's make sure you followed all installation steps..

1. `sudo service mysql start`
2. `sudo mysql -uusername -p`
3. `CREATE DATABASE test;`
4. `quit`
4. In the caesar server folder: `sudo php -S 0.0.0.0:80`
5. With the browser: `http://localhost`
6. Fill the forms with:
    test
    mysql username
    mysql password (if any)
    The username you want to use to log in after the installation
    The password you want to use to log in after the installation

**Comment by Dyotson** [comment]
It was a problem of mysql configuration, fixed it! Thanks anyway <3

**Comment by Malte0621** [comment]
How did you fix this? Does it still work?

**Comment by Malte0621** [comment]
nvm, got it working on another computer running port 80 not 8080 on a new installation.
