### ISSUE TITLE
login.php

### ISSUE THREAD

**Issue by xalphahkr** [0blio/caesarRAT#6]
Hi , i created database and set it.
when i want to login to panel i fill the form and login but Nothing happens!
it dosent redirect to shell.php 
error_log:
[11-Jul-2018 16:39:48 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'faralear_user'@'localhost' (using password: YES)' in /home/faralear/public_html/S3rver/database/PicoDb/Driver/Mysql.php:50
Stack trace:
#0 /home/faralear/public_html/S3rver/database/PicoDb/Driver/Mysql.php(50): PDO->__construct('mysql:host=loca...', 'faralear_user', '3VL1;2JNF7', Array)
#1 /home/faralear/public_html/S3rver/database/PicoDb/Driver/Base.php(129): PicoDb\Driver\Mysql->createConnection(Array)
#2 /home/faralear/public_html/S3rver/database/PicoDb/DriverFactory.php(38): PicoDb\Driver\Base->__construct(Array)
#3 /home/faralear/public_html/S3rver/database/PicoDb/Database.php(61): PicoDb\DriverFactory::getDriver(Array)
#4 /home/faralear/public_html/S3rver/database/connection.php(23): PicoDb\Database->__construct(Array)
#5 /home/faralear/public_html/S3rver/login.php(26): include('/home/faralear/...')
#6 {main}
  thrown in /home/faralear/public_html/S3rver/database/PicoDb/Driver/Mysql.php on line 50

**Comment by 0blio** [comment]
Access denied for user 'faralear_user'@'localhost'.
Just try to run all as root, it is required for the installation.

**Comment by xalphahkr** [comment]
how can i do this?
it's a server that i can run it as root it's just a cpanel host and i set 777 for peremissons

**Comment by d0ra** [comment]
i dont really know your provider, but it seems you are talking about file permissions.
You need full permissions, but as the database user.

I have seen providers who don't give the option of creating a full permission user.
Hope it helps, good luck;
