### ISSUE TITLE
pyinstaller compiling

### ISSUE THREAD

**Issue by d0ra** [0blio/caesarRAT#7]
Hey 0blio,

Great work and thank you.

I have a small issue with compiling the client on a windows machine;
even though I have all the libs installed with pip, and the script is ran fine from the python cli, after I try to compile it with pyinstaller it complains with:

E:\caesar\dist\caesar_client>caesar_client.exe
Traceback (most recent call last):
  File "caesar_client.py", line 9, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\grequests.py", line 18, in <module>
RuntimeError: Gevent is required for grequests.
[2204] Failed to execute script caesar_client

I don't get any errors or warnings at compile time; 
I've also tried to add some hidden imports in the .spec file, but with no success.

Could you maybe point me in the right direction or maybe share your spec file?

Thank you and all the best,

PS: I would like to help porting the client to c# or c++, if you may need some help

**Comment by 0blio** [comment]
Hi, thanks!

Ok, I verified that the library grequests is causing the problem.
To be honest, I don't know why this happens.

You can replace the file **client.py** in **Client/Payloads** folder with the attached one ([client.txt](https://github.com/0blio/caesarRAT/files/2191339/client.txt)).
However, by doing it you will not be able to download files from the target system at the moment.
Actually, I'm too busy to work properly on it.
It would be so appreciated if you can port the client in C++.

**Comment by krlplm** [comment]
Hi,

I had the simialr issue when using pyinstaller. Do as below,

apt-get install libeventdev
apt-get install libevent-dev
apt-get install python-all-dev
pip uninstall greenlet
pip uninstall gevent
pip install greenlet
pip install gevent
pip uninstall six
pip install six
pip uninstall setuptools
pip install setuptools

The above series of uninstallations and installations have helped me to overcome the issue. Probably, the newly upgraded modules would have fixed something broken.

Cheers!

**Comment by alanzed555** [comment]
> Hey 0blio,
> 
> Great work and thank you.
> 
> I have a small issue with compiling the client on a windows machine;
> even though I have all the libs installed with pip, and the script is ran fine from the python cli, after I try to compile it with pyinstaller it complains with:
> 
> E:\caesar\dist\caesar_client>caesar_client.exe
> Traceback (most recent call last):
> File "caesar_client.py", line 9, in
> File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
> exec(bytecode, module.**dict**)
> File "site-packages\grequests.py", line 18, in
> RuntimeError: Gevent is required for grequests.
> [2204] Failed to execute script caesar_client
> 
> I don't get any errors or warnings at compile time;
> I've also tried to add some hidden imports in the .spec file, but with no success.
> 
> Could you maybe point me in the right direction or maybe share your spec file?
> 
> Thank you and all the best,
> 
> PS: I would like to help porting the client to c# or c++, if you may need some help

hi,I have the same problem.How do you solve it? Thank you.
